/**
 * Build the Explorer from this checkout, never from an external API.
 * The checked-in generated module is a fallback when git is unavailable.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const target = resolve('src/generated/repositoryFiles.ts');
let paths: string[];
try {
  paths = execFileSync('git', ['ls-files', '--cached', '-z'], { encoding: 'utf8' })
    .split('\0')
    .filter(Boolean)
    .filter(path => !path.includes('/node_modules/') && !path.startsWith('.env'));
} catch {
  console.warn('git ls-files unavailable. Keeping the checked-in Explorer snapshot.');
  process.exit(0);
}
if (!paths.length) {
  console.warn('No tracked files found. Keeping the checked-in Explorer snapshot.');
  process.exit(0);
}
paths.sort((a, b) => a.localeCompare(b, 'en'));
const previewPattern = /^(?:README\.md|package\.json|tsconfig\.json|vite\.config\.ts|vercel\.json|\.gitignore|src\/(?:[^/]+\/)*[^/]+\.(?:ts|tsx|css))$/;
const previews: Record<string, string> = {};
for (const path of paths) {
  if (!previewPattern.test(path)) continue;
  try {
    const source = readFileSync(path, 'utf8');
    // Small, real tracked snippets for a responsive, offline source preview.
    previews[path] = source.length <= 12000
      ? source
      : source.slice(0, 12000) + '\n// …';
  } catch { /* A file deleted between git ls-files and reading is harmless. */ }
}
writeFileSync(target,
  '// Generated by scripts/generate-repo-tree.ts — do not edit manually.\n' +
  'export const repositoryFiles: string[] = ' + JSON.stringify(paths, null, 2) + ';\n' +
  'export const repositoryPreviews: Record<string, string> = ' + JSON.stringify(previews, null, 2) + ';\n',
  'utf8');
console.log('Explorer updated from ' + paths.length + ' tracked files.');
